const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const defaults={public:[{label:"BICHO DO DIA",title:"Pavão",text:"Destaque demonstrativo do dia.",numbers:["1973","1974","1975","1976"]}],vip:[{label:"EXCLUSIVO",title:"Palpite VIP 1",text:"Conteúdo reservado para membros.",numbers:["9013","7814","4515","7116"]}],notices:[{id:"default-notice",title:"Aviso importante",text:"Confira sempre os horários.",important:false}],files:[{title:"Tabela de horários",text:"Arquivo demonstrativo.",url:"#"}]};
const get=(k,d)=>JSON.parse(localStorage.getItem(k)||"null")||d;const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function render(){renderList("publicList","portal_public_posts",defaults.public);renderList("vipList","portal_vip_posts",defaults.vip);renderList("noticeListAdmin","portal_vip_notices",defaults.notices);renderList("fileListAdmin","portal_vip_files",defaults.files)}
function renderList(id,key,def){const arr=get(key,def);$("#"+id).innerHTML=arr.map((x,i)=>`<article class="notice-item"><div><strong>${x.title}</strong>${x.important?'<span class="important-admin-badge">IMPORTANTE</span>':''}</div><p>${x.text||""}</p><button class="btn secondary" onclick="removeItem('${key}',${i})">Excluir</button></article>`).join("")}
window.removeItem=(key,i)=>{const map={"portal_public_posts":defaults.public,"portal_vip_posts":defaults.vip,"portal_vip_notices":defaults.notices,"portal_vip_files":defaults.files};const arr=get(key,map[key]);arr.splice(i,1);set(key,arr);render()}
$("#adminLoginBtn").onclick=()=>{if($("#adminUser").value==="admin"&&$("#adminPass").value==="admin123"){$("#adminLogin").classList.add("hidden");$("#adminDashboard").classList.remove("hidden");sessionStorage.setItem("admin","1");render()}else $("#adminMsg").textContent="Usuário ou senha incorretos."}
$("#adminLogout").onclick=()=>{sessionStorage.removeItem("admin");location.reload()}
$$("[data-admin]").forEach(b=>b.onclick=()=>{$$("[data-admin]").forEach(x=>x.classList.remove("active"));$$(".tool-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.admin).classList.add("active")})
$("#addPublic").onclick=()=>{const a=get("portal_public_posts",defaults.public);a.unshift({label:"PALPITE",title:$("#pubTitle").value,text:$("#pubText").value,numbers:$("#pubNumbers").value.split(/\s+/).filter(Boolean)});set("portal_public_posts",a);render()}
$("#addVip").onclick=()=>{const a=get("portal_vip_posts",defaults.vip);a.unshift({label:"EXCLUSIVO",title:$("#vipTitle").value,text:$("#vipText").value,numbers:$("#vipNumbers").value.split(/\s+/).filter(Boolean)});set("portal_vip_posts",a);render()}
$("#addNotice").onclick=()=>{const a=get("portal_vip_notices",defaults.notices);const important=$("#noticeImportant").checked;if(important)a.forEach(item=>item.important=false);a.unshift({id:String(Date.now()),title:$("#noticeTitle").value,text:$("#noticeText").value,important});set("portal_vip_notices",a);$("#noticeTitle").value="";$("#noticeText").value="";$("#noticeImportant").checked=false;render()}
$("#addFile").onclick=()=>{const a=get("portal_vip_files",defaults.files);a.unshift({title:$("#fileTitle").value,text:$("#fileText").value,url:$("#fileUrl").value||"#"});set("portal_vip_files",a);render()}
if(sessionStorage.getItem("admin")==="1"){$("#adminLogin").classList.add("hidden");$("#adminDashboard").classList.remove("hidden");render()}
